version: '3.8'
services:
  web:
    image: mwar8205/r00txtr1-tailadmin-laravel:beta
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: r00t
      MYSQL_USER: r00t
      MYSQL_PASSWORD: r00t
      MYSQL_ROOT_PASSWORD: r00t
    ports:
      - "3307:3306"
