name: Laravel application (Mysql)
run-name: Build, Push and Deploy image simple social media
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "afrisyah/afrisyah-tailadmin-laravel:beta"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker image ls
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push Image
        run: docker push $IMAGE_NAME

  deploy-social-media:
    needs: build-push-image
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: stop and remove existing container
        run: docker compose down --rmi all
      - name: start container
        run: docker compose up -d
